apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: neuraserver-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: neuraserver-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
