[package]
name = "neuraserver"
version = "1.0.0"
edition = "2024"

[dependencies]
rdkafka = { version = "0.27", features = ["produce", "consume", "rdkafka"] }
zookeeper = "0.6"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
